# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Bluetooth' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Bluetooth
  pod 'BabyBluetooth','~> 0.7.0'
  pod 'MBProgressHUD'

end
