# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'QiNiuVideoPlayer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Masonry'
  pod 'PLPlayerKit'   #七牛视频播放

  # Pods for QiNiuVideoPlayer

end
