# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PushNotificationDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PushNotificationDemo
  pod 'JCore', '2.1.4'
  pod 'JPush', '3.2.6'
  pod 'SVProgressHUD'
end
